apiVersion: apps/v1
kind:  
metadata:
  name: 
  labels:
    app: 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:


---

apiVersion: v1
kind: Service
metadata:
  name: 
spec:
