apiVersion: apps/v1
kind: Deployment 
metadata:
  name: 
  labels:
    app: 
spec:
  replicas: 
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: 
        image: mariadb:10-focal
        ports:
        - containerPort: 3306 
        env:



---

apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  selector:
    app: 
  ports:
